const ezAlert = require(`./ez-alert`);
const ezButton = require(`./ez-button`);
const ezCheckboxGroup = require(`./ez-checkbox-group`);
const ezHeading = require(`./ez-heading`);
const ezInput = require(`./ez-input`);
const ezRadioGroup = require(`./ez-radio-group`);
const ezSelect = require(`./ez-select`);
const ezSpace = require(`./ez-space`);
const ezTextArea = require(`./ez-text-area`);

module.exports.EZAlert = ezAlert.EZAlert;
module.exports.EZButton = ezButton.EZButton;
module.exports.EZCheckboxGroup = ezCheckboxGroup.EZCheckboxGroup;
module.exports.EZHeading = ezHeading.EZHeading;
module.exports.EZInput = ezInput.EZInput;
module.exports.EZRadioGroup = ezRadioGroup.EZRadioGroup;
module.exports.EZSelect = ezSelect.EZSelect;
module.exports.EZSpace = ezSpace.EZSpace;
module.exports.EZTextArea = ezTextArea.EZTextArea;
